"""adds year to cards

Revision ID: 421e73f95a16
Revises: a61d2f9096e4
Create Date: 2022-07-29 15:21:42.315108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421e73f95a16'
down_revision = 'a61d2f9096e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'year')
    # ### end Alembic commands ###
